# Generated by Django 5.2.7 on 2025-10-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address_history',
            field=models.CharField(blank=True, default='Confirmed & Verified', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='address_history_details',
            field=models.TextField(blank=True, help_text='Detailed address history information'),
        ),
        migrations.AddField(
            model_name='report',
            name='county_criminal_records',
            field=models.TextField(blank=True, default='No records found'),
        ),
        migrations.AddField(
            model_name='report',
            name='county_searched',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='database_match',
            field=models.CharField(blank=True, default='100% Match', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='education_degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='education_graduation_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='report',
            name='education_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='education_status',
            field=models.CharField(blank=True, default='Confirmed by Registrar', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='education_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='employment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='employment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='federal_criminal_records',
            field=models.TextField(blank=True, default='No records found in federal databases'),
        ),
        migrations.AddField(
            model_name='report',
            name='final_summary',
            field=models.TextField(blank=True, default='Has successfully passed all required checks with no adverse findings.'),
        ),
        migrations.AddField(
            model_name='report',
            name='identity_cross_reference',
            field=models.CharField(blank=True, default='Nothing Found', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Additional recommendations or notes'),
        ),
        migrations.AddField(
            model_name='report',
            name='sex_offender_registry',
            field=models.TextField(blank=True, default='No matches found'),
        ),
        migrations.AddField(
            model_name='report',
            name='ssn_validation',
            field=models.CharField(blank=True, default='Valid & Matches Records', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='state_criminal_records',
            field=models.TextField(blank=True, default='No records found'),
        ),
        migrations.AddField(
            model_name='report',
            name='state_searched',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('clear', 'Clear'), ('pending_review', 'Pending Review'), ('flagged', 'Flagged')], default='clear', max_length=20),
        ),
    ]
