# Generated by Django 5.2.7 on 2025-10-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_requests', '0002_report_address_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='sex_offender_registry',
            new_name='adult_offender_registry',
        ),
    ]
