# Generated by Django 5.2.7 on 2025-11-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_requests', '0003_rename_sex_offender_registry_report_adult_offender_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for this report', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed')], default='payment_pending', help_text='Payment status for this report', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='report_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Report - $25'), ('premium', 'Premium Report - $50')], help_text='Type of report selected by user', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='Stripe checkout session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=255, null=True),
        ),
    ]
