# Generated by Django 5.2.7 on 2025-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/'),
        ),
    ]
