# Generated by Django 5.2.7 on 2025-10-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='feature_key',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
