# Generated by Django 5.2.7 on 2025-11-09 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Payment Histories'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_per_report']},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='advanced_reports',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='basic_identity_verification',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='bulk_requests',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='criminal_records_search',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='federal_records_search',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_requests_per_month',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='requests_used_this_month',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='trial_end',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Which plan was used for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='reports_purchased',
            field=models.IntegerField(default=1, help_text='Number of reports purchased in this transaction'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='identity_verification',
            field=models.BooleanField(default=False, help_text='Identity Verification'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='national_criminal_search',
            field=models.BooleanField(default=False, help_text='National Criminal Search'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_per_report',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Price charged per background check report', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sex_offender_registry',
            field=models.BooleanField(default=False, help_text='Sex Offender Registry'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ssn_trace',
            field=models.BooleanField(default=False, help_text='SSN Trace'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_county_search',
            field=models.BooleanField(default=False, help_text='Unlimited County Criminal Search'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='free_trial_date',
            field=models.DateTimeField(blank=True, help_text='When the free trial was used', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='free_trial_used',
            field=models.BooleanField(default=False, help_text='Has the user used their 1 free search trial'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='total_reports_purchased',
            field=models.IntegerField(default=0, help_text='Total number of reports user has purchased'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='total_reports_used',
            field=models.IntegerField(default=0, help_text='Total number of reports user has used'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for the report', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='education_verification',
            field=models.BooleanField(default=False, help_text='Education Verification'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='employment_verification',
            field=models.BooleanField(default=False, help_text='Employment History'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
