# Generated by Django 5.2.7 on 2025-10-23 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admin_to_user', 'Admin to User'), ('user_to_admin', 'User to Admin'), ('system', 'System')], default='admin_to_user', help_text='Type of notification', max_length=20)),
                ('category', models.CharField(choices=[('background_check', 'Background Check'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('report', 'Report'), ('general', 'General')], default='general', help_text='Category of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., Request, Report, Subscription)', max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL for action button in notification', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent this notification (null for system notifications)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx'), models.Index(fields=['category', '-created_at'], name='notificatio_categor_6dc2ff_idx')],
            },
        ),
    ]
